query authorizedTargets(
  $namespace: String!
  $resourceType: ResourceType!
  $resource: String!
  $targetType: PolicyAssignmentTargetType
  $actions: AuthorizedTargetsActionsInput
) {
  authorizedTargets(
    namespace: $namespace
    resource: $resource
    resourceType: $resourceType
    targetType: $targetType
    actions: $actions
  ) {
    totalCount
    list {
      targetType
      targetIdentifier
      actions
    }
  }
}
