query emailTemplates{
    emailTemplates{
        type
        name
        subject
        sender
        content
        redirectTo
        hasURL
        expiresIn
        enabled
        isSystem
    }
}