query groups($userId: String, $page: Int, $limit: Int, $sortBy: SortByEnum){
    groups(userId: $userId, page: $page, limit: $limit, sortBy: $sortBy){
        totalCount
        list{
            code
            name
            description
            createdAt
            updatedAt
        }
    }
}