query listGroupAuthorizedResources(
  $code: String!
  $namespace: String
  $resourceType: String
) {
  group(code: $code) {
    authorizedResources(namespace: $namespace, resourceType: $resourceType) {
      totalCount
      list {
        code
        type
        actions
      }
    }
  }
}
