query socialConnectionInstance($provider: String!){
    socialConnectionInstance(provider: $provider){
        provider
        enabled
        fields{
            key
            value
        }
    }
}