query socialConnections{
    socialConnections{
        provider
        name
        logo
        description
        fields{
            key
            label
            type
            placeholder
        }
    }
}